#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("BookList.Resource", IsApplication=true)]

namespace BookList
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int AddTitle = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int AudioBookCheckBox = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int Delete = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int EditTitle = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int Finish = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int NumberOfPages = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int addBook = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int bookList = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int totalHours = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int totalPages = 2131099656;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int AddBook = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int BookDetail = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Main = 2130968578;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int book_icon = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int icon = 2130903041;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050004
			public const int AddPage = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int Delete = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int FinishEdit = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int add_page = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int add_page_greeting = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int titleHint = 2131034117;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
